### ISSUE TITLE
Address TODO in release_notes.yml

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/newrelic-ruby-agent#1919]
### Description
`release_notes.yml` includes the TODO: `Add a job to delete branch on PR failure.`

In this action, a branch is created to push release note changes to. If the action fails after this branch is created, we cannot successfully re-run the action without seeing a branch name collision. We must first delete the branch and re-run the job. A job to automatically delete the branch on action failure would solve this. 

Thoughts: Check out the newrelic-ruby-agent repository to access the recently created branch_name through `generate_release_notes.rb`. Then carry that name (as an env var) to the next step of checking out newrelic/docs-website to delete the branch. If it is possible to carry the branch_name env var between yml jobs, we could also use that. 

Here are some initial code thoughts (not working):

```
  delete_branch_on_fail:
    name: Delete branch on fail
    needs: [send-pull-requests]
    runs-on: ubuntu-22.04
    if: always()
    steps:

# Checkout newrelic-ruby-agent
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: newrelic/newrelic-ruby-agent
      - name: Get branch name
        run: echo "branch_name=$(ruby -r /home/runner/work/newrelic-ruby-agent/newrelic-ruby-agent/.github/workflows/scripts/generate_release_notes.rb -e GenerateReleaseNotes.new.branch_name)" >> $GITHUB_ENV

# Check out docs-website and delete branch
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: newrelic/docs-website
          token: ${{ secrets.NEWRELIC_RUBY_AGENT_BOT_TOKEN }}
      - name: Build delete command
        run: echo "delete_branch=git push origin --delete --force ${{env.branch_name}}" >> $GITHUB_ENV
      - name: Delete branch
        uses: technote-space/workflow-conclusion-action@v3
      - run: ${{env.delete_branch}}
        if: ${{ env.WORKFLOW_CONCLUSION == 'failure' && github.event_name != 'workflow_dispatch' }}
```
