### ISSUE TITLE
Running out Active Record connections after upgrading from 8 to 9

### ISSUE THREAD

**Issue by NielsKSchjoedt** [newrelic/newrelic-ruby-agent#1935]
After upgrading from 8.x to 9.1 we are seeing some issues on our web servers where we are running our rails app using unicorn in product. After a minute or two, the application starts to run out of db connections like so: 

`ActiveRecord::ConnectionTimeoutError: could not obtain a connection from the pool within 5.000 seconds (waited 5.004 seconds); all pooled connections were in use`

Our database.yml specifies that we have just `pool: 1` for the connections to Postgresql, since Unicorn is single threaded. We have found out that this does not happen if we set the connection pool size to `2`.

How come there is a difference in how many connections the app consumes with the new version of Newrelic?

Also, we have noticed, that if we run agent version 9.1 BUT with the newrelic.yml used under 8.x then the errors does NOT happen:

```yaml
# Old version of newrelic.yml used in with agent version 8 until we upgraded to 9.x
common: &default_settings
  license_key: 'xxx'
  agent_enabled: auto
  app_name: 'AU'
  monitor_mode: true
  developer_mode: false
  log_level: info
  rake:
    tasks: [".+"]
  attributes:
    include:
      - job.sidekiq.args.*
      - job.rake.*
  browser_monitoring:
      auto_instrument: false
  audit_log:
    enabled: false
  distributed_tracing:
    enabled: true
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: raw
    stack_trace_threshold: 0.500
    explain_enabled: false
  error_collector:
    enabled: true
    capture_source: true
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound,ActiveRecord::RecordNotFound,ActionController::UnknownAction,AbstractController::ActionNotFound,Mongoid::Errors::DocumentNotFound,Sinatra::NotFound,Sidekiq::Limiter::OverLimit"
    expected_classes: "CGI::Session::CookieStore::TamperedWithCookie,ActionDispatch::RemoteIp::IpSpoofAttackError,FastAttributes::TypeCast::InvalidValueError,Geo::Errors::UnknownAreaForRegion,CarSearching::Errors::CarModelNotRecognized,ActionController::UnknownFormat"
development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true
test:
  <<: *default_settings
  monitor_mode: false
production:
  <<: *default_settings
  monitor_mode: true
staging:
  <<: *default_settings
  monitor_mode: true
  app_name: AU Staging
```

But as soon at we change the newrelic.yml to the updated one matching version 9.1 then we get the issues.

```yaml
# New version of newrelic.yml updated to match version 9.1 of agent
common: &default_settings
  license_key: 'xxx'
  app_name: 'AU'
  agent_enabled: auto
  log_level: warn
  browser_monitoring.auto_instrument: false
  distributed_tracing.enabled: true
  error_collector.attributes.enabled: true
  error_collector.enabled: true
  error_collector.expected_classes: "CGI::Session::CookieStore::TamperedWithCookie,ActionDispatch::RemoteIp::IpSpoofAttackError,FastAttributes::TypeCast::InvalidValueError,Geo::Errors::UnknownAreaForRegion,CarSearching::Errors::CarModelNotRecognized,ActionController::UnknownFormat"
  instrumentation.thread.tracing: false
  monitor_mode: true
  rake:
    tasks: [.+]
  transaction_tracer.attributes.enabled: true
  transaction_tracer.enabled: true
  transaction_tracer.explain.enabled:  false
  transaction_tracer.record_sql: 'raw'
  transaction_tracer.stack_trace_threshold: 0.5
  transaction_tracer.transaction_threshold: 1.0
development:
  <<: *default_settings
  monitor_mode: false
test:
  <<: *default_settings
  monitor_mode: false
production:
  <<: *default_settings
  monitor_mode: true
staging:
  <<: *default_settings
  monitor_mode: true
  app_name: AU Staging
```

What's the difference in these configs which might cause the application to want to consume more connections to Postgresql?
