### ISSUE TITLE
newrelic & sidekiq 7.2.1 agent injection not working?

### ISSUE THREAD

**Issue by Insood** [newrelic/newrelic-ruby-agent#2427]
## Description
I'm trying to upgrade our Rails 6.1 application to the latest newrelic_rpm (9.7.1) & sidekiq gem versions so that we can upgrade to Rails 7.1.

We have the sidekiq web UI mounted in our application and I'm running into a minor issue where sidekiq does not allow for injecting inline scripts since 7.2 (https://github.com/sidekiq/sidekiq/pull/6074). I'm seeing errors in console along the lines of ```Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https: http:". Either the 'unsafe-inline' keyword, a hash ('sha256-eg5bTdCwlsbd2Ex1VrxAGTrpwcYjEfeImwhVCzs1uJw='), or a nonce ('nonce-...') is required to enable inline execution.```

This script appears to be a newrelic script:

```
        <script type="text/javascript">
            window.NREUM || (NREUM = {});
            NREUM.info = {
                "beacon": "bam.nr-data.net",
                "errorBeacon": "bam.nr-data.net",
```

As far as I can tell all this is affecting is that the browser will not any data from the sidekiq web UI to newrelic.

## Expected Behavior
No console errors or some way to configure new relic to not inject the browser agent at specific paths.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
This issue does not happen with the previous minor release of sidekiq (7.1) leaving me to believe this is due to the above referenced sidekiq security update

## Steps to Reproduce
Please be as specific as possible.
TIP:  Link a sample application that demonstrates the issue. 

## Your Environment
Ruby 3.1.2
Rails 6.1.7.6
newrelic_rpm 9.7.1
sidekiq 7.2.1
sidekiq-ent 7.2.0
sidekiq-pro 7.2.0

```
common: &default_settings
  license_key: abc123

uat:
  <<: *default_settings
  app_name: uat.ourapp.com
  log_level: info
  instrumentation:
    net_http: chain
  distributed_tracing:
    enabled: true
  monitor_mode: true
  application_logging:
    forwarding:
      enabled: true
  attributes.include: job.sidekiq.args.*
```

## Additional context
N/A

## For Maintainers Only or Hero Triaging this bug
N/A
