### ISSUE TITLE
`app_name` using envionment default even when configured in newrelic.yml

### ISSUE THREAD

**Issue by NC-piercej** [newrelic/newrelic-ruby-agent#2846]
## Description
The `app_name` on `NewRelic::Agent.config[:app_name]` is being configured to the default (the environment), even though the `newrelic.yml` config file has an `app_name` provided for that environment.

This seems to be a regression on newer versions of the agent. On earlier versions, the exact same config files and newrelic setup produced the correct `app_name`.

Notably, `NewRelic::Agent.config.fetch(:app_name)` returns the correct value, but the value on `@cache` (which everything actually uses) within `NewRelic::Agent.config` is incorrect. So, something may be going wrong when the agent is first booting up.

We are working around the issue with the following line of code:

```ruby
# correct the newrelic app name, which is broken for unknown reasons
NewRelic::Agent.config.instance_variable_get(:@cache)[:app_name] = NewRelic::Agent.config.fetch(:app_name)
```

## Expected Behavior
The `app_name` configured in `config/newrelic.yml` for the environment is used, not the environment name.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
Provide any other relevant log data.
TIP:  Scrub logs and diagnostic information for sensitive information 

## Steps to Reproduce
- Specify an `app_name` for an environment in `config/newrelic.yml`
- Launch the app, observe that `NewRelic::Agent.config[:app_name]` is incorrectly the environment

Example config:

```
development:
  license_key: "SET_VIA_ENV_VAR"
  app_name: "should-not-be-development"
  agent_enabled: true # agent must be enabled for controller hooks to work
  distributed_tracing:
    enabled: true
  thread_profiler:
    enabled: true
  application_logging:
    forwarding:
      enabled: true
```

NewRelic loaded by:

```
require "newrelic_rpm"
require "new_relic/agent/method_tracer"
```

## Your Environment
Include as many relevant details about your environment as possible including the running version of the Ruby agent, the Ruby version being used and any other relevant environment information

Agent version: 9.13.0
Ruby: JRuby 9.4.8.0 running via the `jruby:9.4.8.0-jdk21` docker image

## Additional context
Add any other context about the problem here. For example, relevant community posts or support tickets.

## For Maintainers Only or Hero Triaging this bug
*Suggested Priority (P1,P2,P3,P4,P5):*
*Suggested T-Shirt size (S, M, L, XL, Unknown):*
