### ISSUE TITLE
Disable log setting not working

### ISSUE THREAD

**Issue by feliperaul** [newrelic/newrelic-ruby-agent#434]
## Description
Even tough `log_level` was set to `off` and `logging.enabled` was set to `false`, I still have 4 ou 5 writes per second to `newrelic_agent.log` file in my production server.

```
common: &default_settings
  log_level: off

  logging:
    enabled: false

production:
  <<: *default_settings
```

## Expected Behavior
It should turn logging off. 

Gem version: `newrelic_rpm (6.11.0.365)`
