### ISSUE TITLE
Expect / Ignore Errors by Class

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#454]
### Is your feature request related to a problem? Please describe.

Implements Expect and Ignore Errors by class, that is, it implements the following configuration options:

```YAML
    ignore_classes:
      - "com.newrelic.ignore.ErrorClass"
      - "com.newrelic.ignore.OtherErrorClass"

    expected_classes:
      - "com.newrelic.ignore.ErrorClass"
      - "com.newrelic.ignore.OtherErrorClass"
```

### Feature Description
This work is based off of the Errors Spec that other New Relic agents have implemented. Below is a summary of the work that needs to be done to expect / ignore errors by class.

* Migrate from `error_collector.ignore_errors` to `error_collector.ignore_classes`
  * The name of the configuration option is changing, but the behavior remains the same.
  * We already implement ignoring errors by class name and by the `ignore_error_filter`, although we are likely to want to clean this code up as we add the ability to expect and ignore errors on other criteria.

* Implement `error_collector.expected_classes`
  * If an error is expected, increment the `ErrorsExpected/all` metric, but do not increment the `Errors/all`, `Errors/[transactionName]`, `Errors/allWeb`, or `Errors/allOther` metrics.
 * If an error is specified in both the ignore and expected lists, the error should be ignored

### Additional context
These are standard configuration options other language agents have implemented.  This Feature Request would bring the Ruby agent in line with the other agents.
