### ISSUE TITLE
Expect / Ignore Errors by message

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#456]
## Feature Description

Errors can be flagged as expected or ignored based on their class and messages.

```YAML
  error_collector:
    enabled: true

    ignore_messages:
      SomeErrorClass:
        - "some error message to ignore"
        - "another error message to ignore"

    expected_messages:
      AnotherErrorClass:
        - "some expected error message"
        - "another expected error message"
```

### Ignore errors by message

* Add error_collector.ignore_messages configuration option
* The option is a hash with string keys that represent the error class and values that are arrays of strings representing the error messages.
* We should not generate errors if the class and error message are matched in the ignore list.

### Expect errors by message

* Add error_collector.expected_messages configuration option
* The option is a hash with string keys that represent the error class and values that are arrays of strings representing the error messages.
* We should mark errors as expected if the class and error message are matched in the expected list.
* If an error is expected, increment the ErrorsExpected/all metric, but do not increment the Errors/all, Errors/[transactionName], Errors/allWeb, or Errors/allOther metrics.

If an error is specified in both the ignore and expected lists, the error should be ignored

### Priority
Should schedule as part of one of the upcoming "bug smash" weeks
