### ISSUE TITLE
Implement skipping CI with "skip ci" in the commit message

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#470]
### Feature Description
Documentation only changes should be skippable in the CI workflow.  Let's add it.

EXAMPLE:
```yaml
jobs:
  main:
    name: Build and test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
```

### Priority
Nice to Have
