### ISSUE TITLE
The agent is not processing newrelic.yml.erb when present.

### ISSUE THREAD

**Issue by mwlang** [newrelic/newrelic-ruby-agent#493]
## Description

The agent is able to parse `newrelic.yml.erb` but fails to list the `.erb` extension in the paths it searches at start up, so an ERB template file is never attempted at load time.

## Expected Behavior
The agent should look for `newrelic.yml.erb` in all the places it looks for `newrelic.yml` and load and parse the ERB template version of the config file when one is found.

## Additional context
Ensure all findable newrelic.yml files are removed in order to discover the `newrelic.yml.erb` version since `newrelic.yml` will take precedence in the discovery process.

## Use Case

1. The user wants to create the `app_name` from within the app
1. Once set, the `app_name` won’t change.
 
The user wants to construct the name from other environment variables. One solution would be if the newrelic.yml parser recognized ERB style interpolation (i.e. <%= %>).

**Comment by mwlang** [comment]
For those who would like to try this feature out ahead of it making it into the next release, simply update your Gemfile entry for the Ruby agent as follows:

Update your Gemfile to:

```ruby
gem 'newrelic_rpm', 
  git: 'https://github.com/newrelic/newrelic-ruby-agent.git', 
  branch: 'configure_with_erb_yml'
```

An example newrelic.yml.erb that uses the ERB templating feature:

```yaml
common: &default_settings
  license_key: <%= ENV['NEWRELIC_LICENSE_KEY'] %>
  app_name: Demo App <%= Rails.env %>

development:
  <<: *default_settings

production:
  <<: *default_settings

test:
  <<: *default_settings
  monitor_mode: false
```
and bundle install and give it a whirl. If this resolves your issues and does not generate deprecation warnings in Ruby 2.7, then we're good to go.
